### ISSUE TITLE
Add support for mongodb Ubuntu 16.04 LTS binaries

### ISSUE THREAD

**Issue by elyas-bhy** [winfinit/mongodb-download#14]
I noticed that when using Ubuntu 16.04 or 16.10, the mongodb binaries for Ubuntu 14.04 were being incorrectly downloaded.

This should be quite straightforward to fix:
In the [getUbuntuVersionString method](https://github.com/winfinit/mongodb-download/blob/9b795866d66454c494b6b72b4df389e3b4eba29c/src/mongodb-download.ts#L499), add something along these lines:
```js
if (major_version >= 16) {  // takes into account both 16.04 and 16.10, since there are no binaries for 16.10
  name += "1604";
} else if (os.release == "14.04") {
  name += "1404";
} // [...]
```

**Comment by winfinit** [comment]
@elyas-bhy Fix is straightforward, however what isn't to me is how 14.x binaries are getting downloaded on 16.x release, so I would like to understand that first, because that is not expected behavior.

**Comment by elyas-bhy** [comment]
Well, it seems that this method defaults to 14.04:
```js
if (os.release == "14.04" || major_version > 14) {
  name += "1404";
} else if // ...
```

Since `major_version` for Ubuntu 16.04 is obviously 16, and 16 > 14, this branch of code is executed and the selected name is `1404`. Does this answer your question?

**Comment by winfinit** [comment]
@elyas-bhy ah! missed greater than, thank you

**Comment by elyas-bhy** [comment]
Hehe it happens :smile:  
Would you mind publishing a release for this fix and updating the dependencies of `mongodb-prebuilt` and `mockgoose`? I found out about this bug while using `mockgoose`. 
Thank you for maintaining these awesome libraries!

**Comment by winfinit** [comment]
@elyas-bhy just published those changes. I did a bit rework on that ubuntu function, because I think it could be a bit more clear. Please let me know if issue is now resolved. Thank you for reporting this issue

**Comment by elyas-bhy** [comment]
Just pulled the updated module and tested again, perfect! :ok_hand: Thank you :)
