### ISSUE TITLE
Fails on debian 9

### ISSUE THREAD

**Issue by petershaw** [winfinit/mongodb-download#30]
Hi, 

on deb-8 everything workes fine, when changing the download url to https like other pull requests mentioned. 
But on deb-9 it hangs on: 
```
Completed: 100 % (94.5mb / 94.5mbb
```
till the timeout. 

some suggestions?

**Comment by omarchehab98** [comment]
Same here. Download fails on Debian 9. Checksum URL is being constructed incorrectly.

Package is requesting https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian-latest.tgz.md5, which responds with a 403.
```
$ uname -a
Linux 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux`
$ cat /etc/debian_version
9.2
```

**Comment by adomenech73** [comment]
Same for me one year after
