### ISSUE TITLE
getos does not currently return release version for SUSE

### ISSUE THREAD

**Issue by mindmelting** [winfinit/mongodb-download#4]
So this line will never work: https://github.com/winfinit/mongodb-download/blob/master/index.js#L93

I do however have a PR I have just opened: https://github.com/wblankenship/getos/pull/26 (I have a feeling this might take a while to get merged)

Given that it will fail for all SUSE platforms, is it worth removing this version dependency for now?

**Comment by winfinit** [comment]
@mindmelting thank you for this report, I am hoping that "getOS" is going to incorporate your change very soon. I am not sure what you mean by removing this version dependency?

**Comment by mindmelting** [comment]
@winfinit I mean removing the check on the release version: https://github.com/winfinit/mongodb-download/blob/master/index.js#L93

**Comment by winfinit** [comment]
@mindmelting so you are proposing to just go for download of suse and ignore version or removing suse block and default to "not supported release" exception? Sorry I didn't look into getos issue that you reported, because I didn't set myself up with suse yet.

**Comment by mindmelting** [comment]
@winfinit you could potentially just download the suse mongo version without checking version.... maybe outputting a warning. I am currently running a shrinkwrapped version using my fork of getos until the PR gets merged, so it doesn't affect me too much right now

**Comment by winfinit** [comment]
I am going to wait for getOS to get fixed, there is no point to commenting it out so just it can go to another exception of unsupported release.

**Comment by mindmelting** [comment]
Fine with me :)

**Comment by mindmelting** [comment]
So that change got merged, and the getos version got bumped to 2.6.0

**Comment by winfinit** [comment]
thank you, i've updated dependency version, and published new release also 1.1.8
