### ISSUE TITLE
Error: unsupported release of Debian 8.2

### ISSUE THREAD

**Issue by franky-continu** [winfinit/mongodb-download#5]
I'm getting this

``` bash
/usr/src/app/node_modules/mongodb-download/index.js:127
throw new Error("unsupported release of Debian " + os.release);
^
Error: unsupported release of Debian 8.2
```

trying to install mongoose

**Comment by winfinit** [comment]
@franky-continu I've checked 7.1 binaries on 8.2 and they are starting, and seem to work fine, so i've updated download to pull 7.1 release

**Comment by franky-continu** [comment]
Fantastic will check them out as soon as I get in, thanks. Will inform here any progress
